[package]
name = "rb-sys"
version = "0.9.0"
edition = "2018"
readme = "readme.md"
categories = ["ruby", "external-ffi-bindings"]
description = "Rust bindings for the CRuby API"
license = "MIT OR Apache-2.0"
repository = "https://github.com/oxidize-rb/rb-sys"
homepage = "https://github.com/oxidize-rb/rb-sys"
documentation = "https://docs.rs/rb-sys"
links = "rb" # we name it like this so users can still use magnus / rutie
build = "build/main.rs"

[features]
default = ["ruby-macros"]
ruby-static = []
link-ruby = []
ruby-macros = ["cc", "shell-words"]

[dependencies]
libc = "0.2.126"

[lib]
doctest = false

[build-dependencies]
bindgen = "0.60"
pkg-config = "0.3.24"
cc = { version = "1.0", optional = true }
shell-words = { version = "1.1.0", optional = true }
lazy_static = "1.4"
linkify = "0.8"
