---
name: CI

on: [push, pull_request]

jobs:
  lint:
    name: 💅 Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
        with:
          rust_toolchain: stable
          ruby_version: '3.0'
          os: ubuntu-latest
      - uses: actions-rs/cargo@v1
        name: ✂️ Run clippy
        with:
          command: clippy
      - uses: actions-rs/cargo@v1
        name: 📃 Run cargo fmt
        with:
          command: fmt

  build_and_test:
    name: 🧪 Build and test
    env:
      RUBY_LINK: "true"
    strategy:
      fail-fast: false
      matrix:
        ruby_version: ['2.4', '2.5', '2.6', '2.7', '3.0', '3.1', 'head']
        sys:
          - os: ubuntu-latest
            rust_toolchain: stable
          - os: macos-latest
            rust_toolchain: stable
          - os: windows-2019
            rust_toolchain: stable-x86_64-pc-windows-gnu
    runs-on: ${{ matrix.sys.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
        with:
          rust_toolchain: ${{ matrix.sys.rust_toolchain }}
          ruby_version: ${{ matrix.ruby_version }}
          os: ${{ matrix.sys.os }}
      - name: 🛠 Cargo build
        working-directory: crates/rb-sys
        run: cargo build --locked --release --verbose
      - name: 🧪 Cargo test
        working-directory: crates/rb-sys
        run: cargo test
      - name: 💨 Smoke test
        if: ${{ matrix.sys.os == 'ubuntu-latest' }}
        working-directory: examples/simple
        run: cargo make verify --verbose
