---
name: "CI"

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  lint:
    name: 💅 Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: ./.github/actions/setup
        with:
          rust_toolchain: stable
          ruby_version: "3.1"
          os: ubuntu-latest
      - uses: actions-rs/cargo@v1
        name: ✂️ Run clippy
        with:
          command: clippy
      - uses: actions-rs/cargo@v1
        name: 📃 Run cargo fmt
        with:
          command: fmt
          args: --check
      - name: 🚓 Run Standard.rb
        run: bundle exec standardrb --format github

  build_and_test:
    name: 🧪 Build and test
    strategy:
      fail-fast: false
      matrix:
        ruby_version: ["2.6", "2.7", "3.0", "3.1", "head"]
        sys:
          - os: ubuntu-latest
            rust_toolchain: stable
          - os: macos-latest
            rust_toolchain: stable
          - os: windows-2019
            rust_toolchain: stable-x86_64-pc-windows-gnu
    runs-on: ${{ matrix.sys.os }}
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: ./.github/actions/setup
        with:
          rust_toolchain: ${{ matrix.sys.rust_toolchain }}
          ruby_version: ${{ matrix.ruby_version }}
          os: ${{ matrix.sys.os }}
      - uses: actions-rs/cargo@v1
        name: 🧪 Cargo test
        with:
          command: test
          args: --workspace --exclude rust-reverse
      - name: 💨 Smoke test
        env:
          CARGO_BUILD_PROFILE: "release"
        run: |
          bundle exec rake test:examples
